# App
spring.application.name=mini-task-manager-backend
server.port=8080

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/mini_task_manager
spring.datasource.username=postgres
spring.datasource.password=b72e4416

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=3d8f2b1a9c7e4f6d0a5b8c3e1f9d2a7b4c6e8f0d3a5b7c9e1f2d4a6b8c0e3f5
jwt.expiration=86400000