-- =============================================
-- Mini Task Management System - Database Schema
-- =============================================

-- Table: public.users
-- (Create users first — tasks has a foreign key referencing it)

CREATE TABLE IF NOT EXISTS public.users
(
    id        bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email     character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    password  character varying(255) NOT NULL,
    role      character varying(255) NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
    CONSTRAINT users_role_check CHECK (role::text = ANY (ARRAY['ADMIN'::character varying, 'USER'::character varying]::text[]))
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users OWNER TO postgres;

-- Table: public.tasks

CREATE TABLE IF NOT EXISTS public.tasks
(
    id          bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at  timestamp(6) without time zone,
    description text,
    due_date    date,
    priority    character varying(255) NOT NULL,
    status      character varying(255) NOT NULL,
    title       character varying(255) NOT NULL,
    updated_at  timestamp(6) without time zone,
    user_id     bigint NOT NULL,
    CONSTRAINT tasks_pkey PRIMARY KEY (id),
    CONSTRAINT fk6s1ob9k4ihi75xbxe2w0ylsdh FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT tasks_priority_check CHECK (priority::text = ANY (ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying]::text[])),
    CONSTRAINT tasks_status_check CHECK (status::text = ANY (ARRAY['TODO'::character varying, 'IN_PROGRESS'::character varying, 'DONE'::character varying]::text[]))
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tasks OWNER TO postgres;